env:
  - GO111MODULE=on
dist: dist
before:
  hooks:
    - go mod download
builds:
- id: nfcuid-windows-amd64
  env:
  - CGO_ENABLED=1
  - CC=x86_64-w64-mingw32-gcc
  - CXX=x86_64-w64-mingw32-g++
  goos:
    - windows
  goarch:
    - amd64
- id: nfcuid-linux-amd64
  env:
  - CGO_ENABLED=1
  goos:
    - linux
  goarch:
    - amd64

archives:    
- id: default
  builds:
  - nfcuid-linux-amd64
  - nfcuid-windows-amd64
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_{{ .Version }}"
  files:
    - config.yaml.example
    - sound.mp3
    - README.md
    - LICENSE
    - INSTALLATION.md
  format_overrides:
    - goos: windows
      format: zip
release:
  github:
    owner: Nemorit-UG
    name: nfcuid
  ids:
    - default
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
